# Generated by Django 4.2.14 on 2024-11-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
                ('fec_pago', models.DateField(blank=True, null=True)),
                ('pagado', models.BooleanField(blank=True, null=True)),
                ('prim_venc', models.DateField(blank=True, null=True, verbose_name='Primer Vencimiento')),
                ('seg_venc', models.DateField(blank=True, null=True, verbose_name='Segundo Vencimiento')),
                ('importe', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
